### PR TITLE
Add game phases to acpl chart

### LINKED ISSUE #437: Add game phases to summary chart
Currently the game summary chart is missing the vertical bars indicating the different phases of the game, like we can see in this screenshot from the website:

Capture d’écran 2024-01-04 à 11 47 37

Endpoint where to retrieve data:
https://lichess.org/api#tag/Games/operation/gamePgn

Look for a `division` json field.

### PR DESCRIPTION
**Pull request by julien4215**
Closes #437

<details><summary>Screenshot</summary>

</details>

### CODE REVIEW

**Comment by HaonRekcef** [comment]
Do we want to utilize vertical space for this? I'd prefer the text to be vertical, similar to the layout in the lichobile app and on lichess.

**Comment by veloce** [comment]
Yes that would be better, and with a smaller font size too.

**Comment by julien4215** [comment]
I also wanted to put the text vertically but the library FL Chart doesn't give this option. Should I create an issue on their GitHub ?

**Comment by veloce** [comment]
Yep, sure. If it's not too difficult you could maybe also submit a PR in their repo to boost the process? Otherwise I don't think we'll merge this, as to me vertical font is mandatory.

**Comment by veloce** [comment]
Perhaps we can still merge this after all, but font size should be smaller and if possible the lines thinner. Also they could be of same color as in lichess website.

**Comment by julien4215** [comment]
I made the lines thinner and I took the same color that is in lichess website. I also made the font smaller.

> Yep, sure. If it's not too difficult you could maybe also submit a PR in their repo to boost the process? Otherwise I don't think we'll merge this, as to me vertical font is mandatory.

Sure I'll look at their repo and try to make a PR.

**Comment by julien4215** [comment]
I made the PR imaNNeo/fl_chart#1579.

**Pull request merged**
