### PR TITLE
add multidex as an android dependency

### PR DESCRIPTION
**Pull request by brandonguigo**
Add `com.android.support:multidex` into `android/app/build.gradle` to support multidex

Closes: #525

### CODE REVIEW

**Comment by veloce** [comment]
I'd like to understand why you have this issue, since there is no problem on my side or with the GitHub action.

Which flutter version do you use? android studio version? thanks.

**Comment by brandonguigo** [comment]
Yes of course. I just bought a new laptop so the Flutter and Android installation are brand new.

**Flutter:** (FVM is used to install the beta channel)
```
```

**Comment by veloce** [comment]
I see from the `flutter --version` output that you're on channel master, not beta. You should switch to beta to work on this project.

**Comment by brandonguigo** [comment]
Sorry, I was missing the fvm prefix to the command ^^

I'm on Flutter 3.19.0-14.0.pre

**Pull request closed without merging**
