### PR TITLE
Fix puzzle streak

### LINKED ISSUE #646: Puzzle Streak: New puzzle streak button doesn't always work after you fail your first puzzle
### What is the problem?

Report from Lichess Forum:
When one plays puzzle streak, after a wrong move one can restart the streak by pressing the play button (right pointing triangle), but if you make a mistake at the first puzzle, the triangle does not work. You can press it multiple times but the puzzle streak does not restart. Sometimes it restarts after couple of presses.

### Steps to reproduce the bug

1: Go to puzzle streak
2: Make an incorrect first move
3: Press the New Puzzle Streak button ( blue triangle)

### What did you expect to happen?

You should be taken to a new puzzle streak session

### What happened instead?

No action happens

### Device Info

Pixel 6

### Operating System Version

Android 14

### Additional information

It happens pretty consistently, although not guaranteed.

### PR DESCRIPTION
**Pull request by julien4215**
Closes #646

### CODE REVIEW

**Comment by HaonRekcef** [comment]
A similar bug seems to exist for puzzle storm. Start a new run, make a move and immediately try to start another run, sometimes the button doesnt work. Can it be fixed the same way?

**Comment by veloce** [comment]
I don't understand how it can fix the bug, since the streak provider is watched and if invalidated should simply build another puzzle controller.

Do you reproduce consistently predictably the issue?

**Comment by julien4215** [comment]
The problem is that it doesn't build another puzzle controller when the provider takes the same values as parameters.

To reproduce the issue, you need to launch a puzzle streak and quickly make a wrong move to launch a new one. The API sends the same set of puzzles during a certain period of time (something like 30 seconds). If you launch a new streak before the API changes its set of puzzle, you will reproduce the issue.

**Comment by julien4215** [comment]
> A similar bug seems to exist for puzzle storm. Start a new run, make a move and immediately try to start another run, sometimes the button doesnt work. Can it be fixed the same way?

I tried to fix it the same way but it didn't work

**Comment by veloce** [comment]
> The problem is that it doesn't build another puzzle controller when the provider takes the same values as parameters.
> 
> 
> 
> To reproduce the issue, you need to launch a puzzle streak and quickly make a wrong move to launch a new one. The API sends the same set of puzzles during a certain period of time (something like 30 seconds). If you launch a new streak before the API changes its set of puzzle, you will reproduce the issue.

I should have read the code comment indeed 😄. Tanks!

**Pull request merged**
