### PR TITLE
Broadcast feature - Show snapshots of games for a round

### PR DESCRIPTION
**Pull request by julien4215**

### CODE REVIEW

**Comment by veloce** [comment]
I'd rather have a list of boards like the puzzle history: it looks like the website and it adapts to tablets.

**Comment by julien4215** [comment]
I don't know how to do that but I'd like to choose julien4215:broadcast as the base branch for this PR

**Comment by veloce** [comment]
You could just close this one and reopen another, couldn't you?

**Comment by veloce** [comment]
It looks much better now btw :)

**Comment by julien4215** [comment]
> You could just close this one and reopen another, couldn't you?

Actually, I can’t create a PR on this repo if the base branch and the compare branch are both from my repository.

**Comment by veloce** [comment]
You can open a single PR for both the list and the boards view if you like.

**Comment by julien4215** [comment]
Sure, I can do that if you don't mind. I thought it would be easier to review if it is separated in multiple PR.

**Pull request closed without merging**
