### PR TITLE
refactor: add common widget for BottomBar

### PR DESCRIPTION
**Pull request by tom-anders**
This gets rid of a lot of code duplication and makes it more straight-forward to build new screens for new features.

Note that the Row in BottomBar now has MainAxisAlignment.spaceAround by default, so it's not necessary anymore to wrap buttons in `Expanded`.

### CODE REVIEW

**Comment by veloce** [comment]
While I think it is a good change, we must be careful it doesn't break some screens. We should make a list of all impacted screens and check they still look fine.

Space around is the same as `Expanded` if all the children are wrapped in an `Expanded`. This may be not the case everywhere (and is why I used `Expanded` instead of `spaceAround` I believe), as you might want to expand some buttons only.

**Comment by tom-anders** [comment]
> While I think it is a good change, we must be careful it doesn't break some screens. We should make a list of all impacted screens and check they still look fine.

I'll add Screenshots for all impacted screens. 👍 

> Space around is the same as `Expanded` if all the children are wrapped in an `Expanded`. This may be not the case everywhere (and is why I used `Expanded` instead of `spaceAround` I believe), as you might want to expand some buttons only.

Yeah that's why I exposed the `mainAxisAlignment` property, so expanding only one of the buttons should still be possible. However, all the current bottoms bars seems to either use `spaceAround` alignment or `Expanded` for all buttons. I can double-check to make sure.

**Comment by tom-anders** [comment]
Analysis:

Screenshot_1725200820

Opening Explorer:

Screenshot_1725200994

Board Editor:

Screenshot_1725200889

Offline Correspondence:

Screenshot_1725200974

Archived Game:

Screenshot_1725201013

Game Loading:

Screenshot_1725201066

Online Game:

Screenshot_1725201122

Puzzle Screen:

Screenshot_1725201175

Puzzle Storm:

Screenshot_1725201191

Puzzle Streak:

Screenshot_1725201210

TV:

Screenshot_1725201308

**Comment by veloce** [comment]
Thanks for the screenshots @tom-anders !

**Review by veloce — APPROVED** [review]

**Pull request merged**
