### PR TITLE
User activity feed

### PR DESCRIPTION
**Pull request by ZTL-UwU**
#24

### CODE REVIEW

**Comment by ZTL-UwU** [comment]
The activity feed is mostly done. However, the size of the list is not ideal. With so many items it generally longer than the screen height, blocking the **Recent Games** section.

640046d2ae446_preview

Should we put the **activity feed** section and the **recent games** section into two separate tabs like the web version.

64004832aad7e_preview

@veloce

**Comment by veloce** [comment]
You should cap the length of that list to a predetermined value, like 10. The header should be tappable (with a three dots on the right, like the leaderboard on home page) and push a detailed screen with the full length list.

**Comment by veloce** [comment]
@ZTL-UwU your PR is still a draft. I think this is a nice feature to have in the app, do you still want to work on it or should I take over?

**Comment by veloce** [comment]
BTW you should not edit manually the `app_en.arb` file. See https://github.com/lichess-org/mobile/blob/main/CONTRIBUTING.md

**Comment by ZTL-UwU** [comment]
@veloce Thank you! I am not very experienced in mobile developing and I found myself not able to cap the length of the list so the pr is kinda suspended. It would be great if you can take over.

**Pull request closed without merging**
