### PR TITLE
Use badge widget for icons

### PR DESCRIPTION
**Pull request by julien4215**
https://api.flutter.dev/flutter/material/Badge/Badge.html

### CODE REVIEW

**Comment by veloce** [comment]
Hi Julien, thanks for this! Can you share a screenshot to show before/after? Thanks!

**Comment by julien4215** [comment]
Before :

After :

**Comment by veloce** [comment]
Nice catch! I didn't know this widget existed.

We need the same color as before I'd say, at least for the chat. The red is too agressive here.

**Comment by julien4215** [comment]
I put the same color as before for the bottom bar button. The font was also heavier before, I don't know if you want to keep it like that.

**Comment by julien4215** [comment]
I changed the style again. Now this is the same as before for both badges. Same font and same color.

**Review by veloce — APPROVED** [review]
👍

**Pull request merged**
