### PR TITLE
feat: add button to expand collapsed variations

### PR DESCRIPTION
**Pull request by tom-anders**
[expand.webm](https://github.com/user-attachments/assets/0d39f689-e8a7-4b5f-81f5-d3e183dcf024)

### CODE REVIEW

**Comment by ijm8710** [comment]
Thanks Tom!❤️

**Review by veloce — APPROVED** [review]
Excellent! Thanks for this.

**Comment by tom-anders** [comment]
@ijm8710 FYI after some discussion in https://github.com/lichess-org/mobile/pull/1111#issuecomment-2462771207 we decided to revert this PR for now, due to several reasons:

- Having the [+] and [-] buttons not in the same place is confusing and a bit irritating when expanind/collapsing variations
- We could have the [+] and [-] at the start of an expanded/collapsed sideline instead, but then the icon is right next to a move button and becomes hard to press
- It's not clear whether collapsing variations is really used that often (by the average user) - Even lichess.org does not display a collapse-button, but requires a right-click instead (but it **does** have the expand-button

**Comment by ijm8710** [comment]
> @ijm8710 FYI after some discussion in https://github.com/lichess-org/mobile/pull/1111#issuecomment-2462771207 we decided to revert this PR for now, due to several reasons:
> 
> 
> 
> - Having the [+] and [-] buttons not in the same place is confusing and a bit irritating when expanind/collapsing variations
> 
> - We could have the [+] and [-] at the start of an expanded/collapsed sideline instead, but then the icon is right next to a move button and becomes hard to press
> 
> - It's not clear whether collapsing variations is really used that often (by the average user) - Even lichess.org does not display a collapse-button, but requires a right-click instead (but it **does** have the expand-button

Hey Tom appreciate you sharing the  heads up, my only hope is that it's temporarily paused while it's rethought rather than becomes abandoned fully. Based on scanning the comments in the pr you shared I think that's the case, but hopefully I'm reading that right.

**Comment by tom-anders** [comment]
> > @ijm8710 FYI after some discussion in [#1111 (comment)](https://github.com/lichess-org/mobile/pull/1111#issuecomment-2462771207) we decided to revert this PR for now, due to several reasons:
> > 
> > * Having the [+] and [-] buttons not in the same place is confusing and a bit irritating when expanind/collapsing variations
> > * We could have the [+] and [-] at the start of an expanded/collapsed sideline instead, but then the icon is right next to a move button and becomes hard to press
> > * It's not clear whether collapsing variations is really used that often (by the average user) - Even lichess.org does not display a collapse-button, but requires a right-click instead (but it **does** have the expand-button
> 
> Hey Tom appreciate you sharing the heads up, my only hope is that it's temporarily paused while it's rethought rather than becomes abandoned fully. Based on scanning the comments in the pr you shared I think that's the case, but hopefully I'm reading that right.

We had some more discussion via DM about this, but the bullet points above are pretty much a summary - I think we should at least see if there's more feedback about this in the future.

**Pull request merged**
